remote_theme: open-sdg/open-sdg@1.1.0
country:
  name: Config interface test
  adjective: Config test
create_goals:
  layout: goal
create_indicators:
  layout: indicator
create_pages:
  - filename: index.html
    folder: /
    layout: frontpage-alt
  - filename: index.html
    folder: /goals
    layout: goals
  - filename: index.html
    folder: /reporting-status
    layout: reportingstatus
  - filename: indicators.json
    folder: /
    layout: indicators.json
  - filename: index.html
    folder: /search
    layout: search
  - filename: index.html
    folder: /news
    layout: news
custom_css: []
custom_js: []
data_edit_url: 'http://prose.io/#my-org/my-repo/edit/develop/data/indicator_[id].csv'
disclaimer:
  phase: beta
  message: This website is currently in beta phase
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com
environment: staging
footer_menu:
  - path: 'mailto:my-email-address@example.com'
    translation_key: menu.contact_us
  - path: 'https://twitter.com/MyTwitterAccount'
    translation_key: general.twitter
frontpage_cards: []
frontpage_goals_grid:
  title: Goals grid
  description: Below is the **Goals grid**
frontpage_heading: This is the frontpage
frontpage_instructions: Take a look around this site for SDG data
frontpage_introduction_banner:
  title: Welcome
  description: Welcome to this Open SDG platform. Take a look around
goal_image_base: 'https://open-sdg.github.io/sdg-translations/assets/img/goals'
goals_page:
  title: Goals page
  description: This is the Goals page
graph_color_set: goal
graph_color_list:
  - ''
graph_color_number: 8
hide_empty_metadata: false
languages:
  - en
menu:
  - path: /reporting-status
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /news
    translation_key: menu.news
metadata_edit_url: 'http://prose.io/#my-org/my-repo/edit/develop/meta/[id].md'
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins
remote_data_prefix: 'https://my-github-org.github.io/my-data-repository'
